# ===================================================================
# Spring Boot configuration for the "dev" profile.
#
# This configuration overrides the application.yml file.
#
# More information on profiles: https://www.jhipster.tech/profiles/
# More information on configuration properties: https://www.jhipster.tech/common-application-properties/
# ===================================================================

# ===================================================================
# Standard Spring Boot properties.
# Full reference is available at:
# http://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
# ===================================================================

logging:
    level:
        ROOT: DEBUG
        io.github.jhipster: DEBUG
        io.proximax.kyc: DEBUG

spring:
    profiles:
        active: dev
        include: swagger
    devtools:
        restart:
            enabled: true
        livereload:
            enabled: false # we use Webpack dev server + BrowserSync for livereload
    jackson:
        serialization.indent_output: true
    data:
        mongodb:
            uri: mongodb://localhost:27017/proximaxKYC
            #uri: mongodb://172.31.24.50:27017/proximaxKYC
    mail:
        host: smtp.zoho.com
        port: 587
        username: kyc.dev@proximax.io  #Replace this field with your Zoho username.
        password: FA28TF4w4Z3X          #Replace this field with your Zoho password.
        protocol: smtp
        tls: true
        from: ProximaX KYC Team
        properties.mail.smtp:
            auth: true
            starttls.enable: true
            ssl.trust: smtp.zoho.com
    messages:
        cache-duration: PT1S # 1 second, see the ISO 8601 standard
    thymeleaf:
        cache: false

# ===================================================================
# To enable SSL, generate a certificate using:
# keytool -genkey -alias proxikyc -storetype PKCS12 -keyalg RSA -keysize 2048 -keystore keystore.p12 -validity 3650
#
# You can also use Let's Encrypt:
# https://maximilian-boehm.com/hp2121/Create-a-Java-Keystore-JKS-from-Let-s-Encrypt-Certificates.htm
#
# Then, modify the server.ssl properties so your "server" configuration looks like:
#
# server:
#    port: 8443
#    ssl:
#        key-store: keystore.p12
#        key-store-password: <your-password>
#        key-store-type: PKCS12
#        key-alias: proxikyc
# ===================================================================
server:
    port: 8085

# ===================================================================
# JHipster specific properties
#
# Full reference is available at: https://www.jhipster.tech/common-application-properties/
# ===================================================================

jhipster:
    http:
        version: V_1_1 # To use HTTP/2 you will need SSL support (see above the "server.ssl" configuration)
    # CORS is only enabled by default with the "dev" profile, so BrowserSync can access the API
    cors:
        allowed-origins: "*"
        allowed-methods: "*"
        allowed-headers: "*"
        exposed-headers: "Authorization,Link,X-Total-Count"
        allow-credentials: true
        max-age: 1800
    security:
        authentication:
            jwt:
                secret: my-secret-token-to-change-in-production
                # Token is valid 24 hours
                token-validity-in-seconds: 86400
                token-validity-in-seconds-for-remember-me: 2592000
    mail: # specific JHipster mail property, for standard properties see MailProperties
        from: kyc.dev@proximax.io
        base-url: http://localhost:9000
    metrics: # DropWizard Metrics configuration, used by MetricsConfiguration
        jmx:
            enabled: true
        logs: # Reports Dropwizard metrics in the logs
            enabled: false
            report-frequency: 60 # in seconds
    logging:
        logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
            enabled: false
            host: localhost
            port: 5000
            queue-size: 512

# ===================================================================
# Application specific properties
# Add your own application properties here, see the ApplicationProperties class
# to have type-safe configuration, like in the JHipsterProperties above
#
# More documentation is available at:
# https://www.jhipster.tech/common-application-properties/
# ===================================================================

application:
    storage-selection: aws-s3 # ipfs | aws-s3
    base-host: http://localhost:8085
    organization:
        name: ProximaX
    security:
        key: WC458XBBMWW74EHSBY66HA60MD7NZJDEDKT2J7XZ1ZPX6ZZ7QC851EME1E4SNQHT
        apikey: WC458XBBMWW74EHSBY66HA60MD7NZJDEDKT2J7XZ1ZPX6ZZ7QC851EME1E4SNQHT
        usingglobal: false
    form:
        validationurl: http://localhost:8085/api/submissions/test/external/validate
        postbackurl: http://localhost:8085/api/submissions/test/external/postback
    ipfs:
        host: /ip4/127.0.0.1/tcp/5001
    amazonProperties:
        accessKey: AKIAZMFN3IGPAQSNMYEM
        secretKey: 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
        bucketName: proximax-kyc-dev
    jumio:
        secret: Mzc2MjY0YWUtNmVmNi00ZWRmLWI4ZWQtYzQ3YjU3YjNlZjRiOjk1ZTIwYVBFZ056bUJieWxJNlpGcG04U0lDcHhONjJt
        url: https://netverify.com/api/netverify/v2/fastfill
    idm:
        user: proximax
        pass: dca91116b595d11144f5c9f2f58e113be283fe2f
        host: https://staging.identitymind.com/im/account/consumer
    thomson:
        url: /v1/
        host: rms-world-check-one-api-pilot.thomsonreuters.com
        key: 6d10456b-5f1d-47d3-90f1-5b5f3d267f6e
        secret: VpHcKfQI8sesvdUGK3un8nW31i7Tf9zKFpZcGirvO87CFi2Ipqxg7sFnFhxOhgjzISOFh+Hu8EQ+E6qZ3blH0g==
        groups: https://rms-world-check-one-api-pilot.thomsonreuters.com/v1/groups
        cases: https://rms-world-check-one-api-pilot.thomsonreuters.com/v1/cases
        profiles: https://rms-world-check-one-api-pilot.thomsonreuters.com/v1/reference/profile/
    shuftipro:
        clientid: aaee0ce51abf0849e68b257ab97d83a36d9d082916b939cd1012f27d7f6bb873
        secret: Q5Rtif09LBFHzI4jqh09Leo8fk06sHBi
        url: https://shuftipro.com/api/
    mailgun:
        username: postmaster@mail.besc.online
        messageurl: https://api:603ee5b6f0068f2dbf2c04332086c722-2b778fc3-2ca80006@api.mailgun.net/v3/mail.besc.online/messages
        password: d40fd693f688eb6824ad270aea7d7b2e-2b778fc3-e10ed8e2
        apikey: 603ee5b6f0068f2dbf2c04332086c722-2b778fc3-2ca80006
        enabled: false
    migration:
        #enabled: true
        enabled: true


