version: '2'
services:
    proxikyc-app:
        image: proxikyc
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATA_MONGODB_URI=mongodb://proxikyc-mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=proxiKYC
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8085:8085
    proxikyc-mongodb:
        extends:
            file: mongodb.yml
            service: proxikyc-mongodb
