export enum DatabaseComponentSubtype {
    DROPDOWN_STANDARD = 'DROPDOWN_STANDARD',
    DROPDOWN_UPLOADBTN = 'DROPDOWN_UPLOADBTN',

    TEXTBOX_ACCOUNT = 'TEXTBOX_ACCOUNT',
    TEXTBOX_ADDRESS = 'TEXTBOX_ADDRESS',
    TEXTBOX_ALPHA = 'TEXTBOX_ALPHA',
    TEXTBOX_EMAIL = 'TEXTBOX_EMAIL',
    TEXTBOX_NUMBER = 'TEXTBOX_NUMBER',
    TEXTBOX_PHONE = 'TEXTBOX_PHONE',
    TEXTBOX_STANDARD = 'TEXTBOX_STANDARD'
}
