export enum TemplateType {
    UNBLOCKED_INPUT = 'UNBLOCKED_INPUT',
    BLOCKED_INPUT = 'BLOCKED_INPUT',
    MODIFIABLE = 'MODIFIABLE',
    MODIFIABLE_UNLOCKED = 'MODIFIABLE_UNLOCKED',
    CHECKBOX_ADAPTED = 'CHECKBOX_ADAPTED' // TODO: remove if no difference with BLOCKED_INPUT
}
