export enum FieldTypes {
    TEXTBOX_ALPHA = 'TEXTBOX_ALPHA',
    TEXTBOX_EMAIL = 'TEXTBOX_EMAIL',
    TEXTBOX_NUMBER = 'TEXTBOX_NUMBER',
    TEXTBOX_PHONE = 'TEXTBOX_PHONE',
    TEXTBOX_STANDARD = 'TEXTBOX_STANDARD',

    TEXT_AREA = 'TEXT_AREA',

    CALENDAR = 'CALENDAR',
    DROPDOWN = 'DROPDOWN',
    CHECKBOX_GROUP = 'CHECKBOX_GROUP',
    RADIO_GROUP = 'RADIO_GROUP',
    GUIDANCE_TEXT = 'GUIDANCE_TEXT',

    UPLOAD_DOCUMENT = 'UPLOAD_DOCUMENT',
    UPLOAD_IMAGE = 'UPLOAD_IMAGE'
}
