export enum FormStatus {
    RESEND = 'RESEND',
    APPROVED = 'APPROVED',
    PENDING_APPROVAL = 'PENDING_APPROVAL',
    REJECTED = 'REJECTED',
    DRAFT = 'DRAFT',
    SUBMITTED = 'SUBMITTED',
    PUBLISHED = 'PUBLISHED',
    FURTHER_APPROVAL = 'ESCALATED',
    ESCALATED = 'ESCALATED',
    SCREENED = 'SCREENED'
}
